sudo: required
services:
  - docker

before_install:
  - docker build  -t george/test-repo -f Dockerfile.dev .

script:
  - docker run george/test-repo npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "test-ci"
  env: "TestCi-env"
  bucket_name: "elasticbeanstalk-us-east-1-861109070356"
  bucket_path: "test-ci"
  on:
    branch: master

  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"